### ISSUE TITLE
Java example

### ISSUE THREAD

**Issue by ilyassesalama** [KaustubhPatange/PayPal-IAP-for-Android#2]
Awesome work, but can we have a Java example, hopefully?

**Comment by KaustubhPatange** [comment]
This wouldn't be hard, all you have to do is open the project in Android Studio and open any kt file then Refactor > Convert to Java.

**Comment by ilyassesalama** [comment]
That option does **not** exist.  And won't be existing since Google is trying to make devs move to Kotlin.

**Comment by KaustubhPatange** [comment]
Rewriting Java from Kotlin is not hard. You don't even need to know Kotlin, there is literally one file in the sample which you need to convert by doing what? renaming "fun to void", adding terminators ';', instead of override add @Override annotation and others can be easily figured out.

Just because you don't want to do it yourself doesn't mean others should do it for you! 

If you can read other peoples code you can do it in one go.

**Comment by ilyassesalama** [comment]
I didn't say that I don't want to do it by myself, it seems like you take stuff too personally. I asked you to provide a Java example politely and you're free to refuse, not to behave like that. 
Anyways, thanks for the explanation.
